apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: anaconda-daemonset
  labels:
    app: anaconda-setup
spec:
  selector:
    matchLabels:
      app: anaconda-setup
  template:
    metadata:
      labels:
        app: anaconda-setup
    spec:
      terminationGracePeriodSeconds: 30 # Set the termination grace period
      automountServiceAccountToken: true
      containers:
      - name: anaconda-setup-container
        image: 126634536477.dkr.ecr.us-east-2.amazonaws.com/addf-eureka-storage-robotic-applications-ecr:ubuntu-ros2
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU, 1 shared gpu is 1GB in g5
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - ALL
        imagePullPolicy: "Always"
        command: ["/bin/bash", "-c", "/usr/local/bin/conda_setup.sh"]
        env:
          - name: BUCKET
            value: "addf-dcv-demo-us-east-2"
        volumeMounts:
          - name: anaconda3
            mountPath: /opt/python_env
          - name: fsx
            mountPath: /mnt/fsx
            readOnly: False
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/check_healthy.sh
          initialDelaySeconds: 0
          periodSeconds: 5
      volumes:
        - name: fsx
          persistentVolumeClaim:
            claimName: fsx-claim
        - name: anaconda3
          hostPath:
            path: "/var/addf/anaconda3"
