apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
provisioner: fsx.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  storageClassName: fsx-sc
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-xxx
    volumeAttributes:
      dnsname: fs-xxx.fsx.${REGION}.amazonaws.com
      mountname: xxx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1200Gi
  storageClassName: fsx-sc
  volumeName: fsx-pv
